model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
adapter_name_or_path: outputs/qwen2.5-0.5b/lora_sft
template: qwen
infer_backend: huggingface  # choices: [huggingface, vllm, sglang, ktransformers]
trust_remote_code: true
